name: My Test Monorepo Project
on:
  push:
      branches:
      - master
      paths:
      - 'apps/frontend/**'
      - 'packages/uibits/**'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarQubeScan1:
    name: SonarQubeScan1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://ambroise.ngrok.io
        with:
          projectBaseDir: apps/frontend/
          args:
            -Dsonar.verbose=true
  sonarQubeScan2:
    name: SonarQubeScan2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://ambroise.ngrok.io
        with:
          projectBaseDir: packages/uibits/
          args:
            -Dsonar.verbose=true
